// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mute": {
            "get": {
                "description": "Mute send event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Mute send event",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Pong",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/resume": {
            "get": {
                "description": "Resume send event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Resume send event",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Current status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get status",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/stop": {
            "get": {
                "description": "Stop send event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Stop send event",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/unmute": {
            "get": {
                "description": "Unmute send event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Unmute send event",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
